# Generated by Django 6.0.7 on 2026-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=20)),
                ('total_donations', models.IntegerField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('days_since_last_donation', models.IntegerField(blank=True, null=True)),
                ('donation_frequency_days', models.IntegerField(blank=True, null=True)),
                ('availability_status', models.CharField(max_length=30)),
                ('eligible_to_donate', models.BooleanField(default=True)),
                ('responded_last_emergency', models.BooleanField(default=False)),
                ('geo_cluster', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
